### PR TITLE
daily mission view bug

### LINKED ISSUE #76: Bug: mission view does not reflect completed photo tasks

### PR DESCRIPTION
**Pull request by brabbuss**
### What does this pull request do?
Fixes where updates to completed task were not reflected without refreshing the page. Now updates automatically

### Issues
closes #76

### CODE REVIEW

File: src/modules/views/MissionControl.jsx [hunk 1]
```diff
@@ -50,10 +50,13 @@ const useStyles = makeStyles(theme => ({
...
-  const [state, dispatch] = useContext(AppContext);
-  
+  const [state, dispatch] = useContext(AppContext);  
   const classes = useStyles()
 
+  useEffect(() => {
+    console.log('effect');
+  })
+
   const makeMissionList = () => {
```
Comment (lo-la-do-li) [inline src/modules/views/MissionControl.jsx:60]: Do we want a user to be able to view/complete missions if they aren't logged in/signed up?

File: src/modules/views/DailyMission.jsx [hunk 2]
```diff
@@ -63,14 +63,14 @@ const DailyMission = props => {
...
+  
   useEffect(async () => {
     await getMissionById(id)
     .then(data => addDataToState("selectedMission", data.data))
     .catch(error => setError(error))
     getMissionTasks(id)
-  }, []);
-
+    console.log('use effect daily mission view');
+  }, [state.selectedTask]);
```
Comment (lo-la-do-li) [inline src/modules/views/DailyMission.jsx:73]: Nice addition of useEffect! It makes sense to update on change in selectedTask

**Review by lo-la-do-li — APPROVED** [review]
Thanks for making these fixes, Scotty!
